#!/bin/bash

# update the system first
sudo apt-get update && sudo apt-get upgrade

# install basic tools
sudo apt-get install -y build-essential vim

# setup basic bash aliases
if [ ! -e ~/.bash_aliases ]; then
    cat << EOF
alias l='ls -ahl --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
EOF
    sudo chown pi:pi ~/.bash_aliases
fi

if [ ! -d ~/bin ]; then
    mkdir ~/bin
    chown -R pi:pi ~/bin

    echo "#!/bin/bash\nvcgencmd measure_temp" > ~/bin/pi-temp
    echo "#!/bin/bash\nvcgencmd get_config int" > ~/bin/pi-config
    echo "#!/bin/bash\nvcgencmd get_mem arm && vcgencmd get_mem gpu" > ~/bin/pi-mem
    echo "#!/bin/bash\nvcgencmd version" > ~/bin/pi-version
fi