#!/bin/bash

if [ "$(id -u)" != "0" -a $EUID -ne 0 ]; then
    IsRoot=0
else
    IsRoot=1
fi

FILE_BASH_ALIASES=~/.bash_aliases
DIR_USER_BIN=~/bin
FILE_PI_TEMP=pi-temp
FILE_PI_CONFIG=pi-config
FILE_PI_MEM=pi-mem
FILE_PI_VERSION=pi-version
FILE_PI_REV=pi-rev

# update the system first
echo "update current system"
sudo apt-get update && sudo apt-get upgrade

# install basic tools
echo "install basic tools"
sudo apt-get install -y build-essential vim

# setup basic bash aliases
echo "setup bash aliases"
if [ ! -e $FILE_BASH_ALIASES ]; then
    cat > $FILE_BASH_ALIASES << EOF
alias l='ls -ahl --color=auto'
alias ..='cd ..'
alias ...='cd ../..'
alias cd..='cd ..'
EOF
    sudo chown pi:pi $FILE_BASH_ALIASES
    . $FILE_BASH_ALIASES
fi

# basic scripts
echo "install basic pi information scripts"
if [ ! -d $DIR_USER_BIN ]; then
    mkdir $DIR_USER_BIN
fi

echo -e '#!/bin/bash\nvcgencmd measure_temp' > $DIR_USER_BIN/$FILE_PI_TEMP
echo -e '#!/bin/bash\nvcgencmd get_config int' > $DIR_USER_BIN/$FILE_PI_CONFIG
echo -e '#!/bin/bash\nvcgencmd get_mem arm && vcgencmd get_mem gpu' > $DIR_USER_BIN/$FILE_PI_MEM
echo -e '#!/bin/bash\nvcgencmd version' > $DIR_USER_BIN/$FILE_PI_VERSION

# overwrite pi-rev everytime
cat > $DIR_USER_BIN/pi-rev << RevEOF
#!/bin/bash

revision=$(cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' | sed 's/^1000//')
awk 'BEGIN { FS=";" } /^'"$revision"'/ { printf "RPi %s %s - PBC-Rev. %s, HW-Rev. %s (%s)\n", $3, $5, $4, $1, $2 }' <<EOF
Beta;Q1 2012;B (Beta); ?;256 MB;Beta Board
0002;Q1 2012;B;1.0;256 MB;
0003;Q3 2012;B (ECN0001);1.0;256 MB;Fuses mod and D14 removed
0004;Q3 2012;B;2.0;256 MB;(Mfg by Sony)
0005;Q4 2012;B;2.0;256 MB;(Mfg by Qisda)
0006;Q4 2012;B;2.0;256 MB;(Mfg by Egoman)
0007;Q1 2013;A;2.0;256 MB;(Mfg by Egoman)
0008;Q1 2013;A;2.0;256 MB;(Mfg by Sony)
0009;Q1 2013;A;2.0;256 MB;(Mfg by Qisda)
000d;Q4 2012;B;2.0;512 MB;(Mfg by Egoman)
000e;Q4 2012;B;2.0;512 MB;(Mfg by Sony)
000f;Q4 2012;B;2.0;512 MB;(Mfg by Qisda)
0010;Q3 2014;B+;1.0;512 MB;(Mfg by Sony)
0011;Q2 2014;Compute Module 1;1.0;512 MB;(Mfg by Sony)
0012;Q4 2014;A+;1.1;256 MB;(Mfg by Sony)
0013;Q1 2015;B+;1.2;512 MB; ?
0014;Q2 2014;Compute Module 1;1.0;512 MB;(Mfg by Embest)
0015; ?;A+;1.1;256 MB / 512 MB;(Mfg by Embest)
a01040;Unknown;2 Model B;1.0;1 GB;(Mfg by Sony)
a01041;Q1 2015;2 Model B;1.1;1 GB;(Mfg by Sony)
a21041;Q1 2015;2 Model B;1.1;1 GB;(Mfg by Embest)
a22042;Q3 2016;2 Model B (with BCM2837);1.2;1 GB;(Mfg by Embest)
900021;Q3 2016;A+;1.1;512 MB;(Mfg by Sony)
900032;Q2 2016?;B+;1.2;512 MB;(Mfg by Sony)
900092;Q4 2015;Zero;1.2;512 MB;(Mfg by Sony)
900093;Q2 2016;Zero;1.3;512 MB;(Mfg by Sony)
920093;Q4 2016?;Zero;1.3;512 MB;(Mfg by Embest)
9000c1;Q1 2017;Zero W;1.1;512 MB;(Mfg by Sony)
a02082;Q1 2016;3 Model B;1.2;1 GB;(Mfg by Sony)
a020a0;Q1 2017;Compute Module 3 (and CM3 Lite);1.0;1 GB;(Mfg by Sony)
a22082;Q1 2016;3 Model B;1.2;1 GB;(Mfg by Embest)
a32082;Q4 2016;3 Model B;1.2;1 GB;(Mfg by Sony Japan)
EOF
RevEOF

if [ ! -e ~/.bash_profile ]; then
    cat > ~/.bash_profile << EOF
#!/bin/bash
[[ -x $DIR_USER_BIN/pi-rev ]] && $DIR_USER_BIN/pi-rev
EOF
fi

chown -R pi:pi $DIR_USER_BIN
chmod +x $DIR_USER_BIN/pi-*